version: "3.9"
services:
  postgres-server:
    container_name: postgres-server
    image: prasetyaip/ems-postgresql:v1
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=DBUSER
      - POSTGRES_PASSWORD=DBPASSWORD
      - POSTGRES_DB=DBNAME
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq-local"
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=userdicoding
  redis:
    image: redis:alpine
    container_name: "redis-local"
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
